# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      - image: ckhrysze/amazonlinux2elixir

    environment:
      MIX_ENV: prod
    working_directory: ~/repo
    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix release
      - run: tar -zcf clustered.tgz _build/prod/rel/clustered

      - store_artifacts:
          path: clustered.tgz
