version: 2
jobs:
  build_release:
    docker:
      - image: ckhrysze/amazonlinux2elixir

    environment:
      MIX_ENV: prod
    working_directory: ~/repo
    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix release
      - run: cp _build/prod/clustered-0.1.0.tar.gz clustered.tgz

      - store_artifacts:
          path: clustered.tgz
